services:
  connect4:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: connect4
    depends_on:
      - mongo
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./configs/config.prod.yaml:/app/config.yaml

  mongo:
    image: mongo:latest
    container_name: connect4_mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
