services:
  connect4:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: connect4
    depends_on:
      - postgres
    restart: on-failure
    env_file: .env
    volumes:
      - ./configs/config.prod.yaml:/app/config.yaml

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: connect_four
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
