name: Build and Deploy Connect Four to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust this to your Go version

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate templ files
        run: templ generate

      - name: Build application
        run: |
          go mod download
          go build -o bin/connect-four

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no bin/connect-four ${USER}@${HOST}:~/connect-four/bin/
          scp -i private_key.pem -o StrictHostKeyChecking=no deploy.sh ${USER}@${HOST}:~/connect-four/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${USER}@${HOST} "
            cd ~/connect-four &&
            chmod +x deploy.sh &&
            COOKIE_SECRET='$COOKIE_SECRET' ./deploy.sh
          "
          rm -f private_key.pem
